Crear una función que permita generar 3 variables cualitativas
ordinales a partir de las variables numéricas con los siguientes criterios:



*   Si es mayor a la “media + 1*desviación estándar” → Alto
*   Si está entre “media - 1*desviación estándar” y “media +
    1*desviación estándar” → Medio
*   Si es menor a la “media - 1*desviación estándar” → Bajo

Nota: Mostrar con las nuevas variables generadas.

Elegir con libertad las variables a trabajar.

La función debe contar con su respectiva documentación.

In [1]:
#importar librerías

import pandas as pd
import numpy as np
df = pd.read_csv('/content/drive/MyDrive/Curso_DataScience_peru/clases/13.2_PROYECTO2_27JULIO2023/autos.csv',delimiter=";")
df.head()

,Millas_Por_Galon,Cilindros,Pais_Origen,Peso_En_Libras,Desplazamiento,Aceleracion,Nombre,Anyo,Caballo_De_Fuerza
0,18.0,8,USA,3504,307.0,12.0,chevrolet chevelle malibu,1/01/1970,130.0
1,15.0,8,USA,3693,350.0,11.5,buick skylark 320,1/01/1970,165.0
2,18.0,8,USA,3436,318.0,11.0,plymouth satellite,1/01/1970,150.0
3,16.0,8,USA,3433,304.0,12.0,amc rebel sst,1/01/1970,150.0
4,17.0,8,USA,3449,302.0,10.5,ford torino,1/01/1970,140.0

In [2]:
#Verificar si tiene datos perdidos/nulos
print('******* Datos perdidos/nulos ******* \n')
print(df.isnull().sum())

******* Datos perdidos/nulos *******

Millas_Por_Galon     8
Cilindros            0
Pais_Origen          0
Peso_En_Libras       0
Desplazamiento       0
Aceleracion          0
Nombre               0
Anyo                 0
Caballo_De_Fuerza    6
dtype: int64

In [3]:
# Se saca una DF con los estadísticos

df.describe()

,Millas_Por_Galon,Cilindros,Peso_En_Libras,Desplazamiento,Aceleracion,Caballo_De_Fuerza
count,398.000000,406.000000,406.000000,406.000000,406.000000,400.000000
mean,23.514573,5.475369,2979.413793,194.779557,15.519704,105.082500
std,7.815984,1.712160,847.004328,104.922458,2.803359,38.768779
min,9.000000,3.000000,1613.000000,68.000000,8.000000,46.000000
25%,17.500000,4.000000,2226.500000,105.000000,13.700000,75.750000
50%,23.000000,4.000000,2822.500000,151.000000,15.500000,95.000000
75%,29.000000,8.000000,3618.250000,302.000000,17.175000,130.000000
max,46.600000,8.000000,5140.000000,455.000000,24.800000,230.000000

In [4]:
mean_Millas_Por_Galon = df['Millas_Por_Galon'].mean()
mean_Millas_Por_Galon = round(mean_Millas_Por_Galon,2)
print(mean_Millas_Por_Galon)

mean_Caballo_De_Fuerza = df['Caballo_De_Fuerza'].mean()
mean_Caballo_De_Fuerza = round(mean_Caballo_De_Fuerza,2)
print(mean_Caballo_De_Fuerza)

23.51
105.08

In [6]:
#Cambiar datos NaN por el promedio o media de la columna

df['Millas_Por_Galon'] = df['Millas_Por_Galon'].replace(np.nan, mean_Millas_Por_Galon )
df['Caballo_De_Fuerza'] = df['Caballo_De_Fuerza'].replace(np.nan, mean_Caballo_De_Fuerza)

#Verificar si tiene datos perdidos/nulos
print('******* Datos perdidos/nulos ******* \n')
print(df.isnull().sum())

******* Datos perdidos/nulos *******

Millas_Por_Galon     0
Cilindros            0
Pais_Origen          0
Peso_En_Libras       0
Desplazamiento       0
Aceleracion          0
Nombre               0
Anyo                 0
Caballo_De_Fuerza    0
dtype: int64

In [7]:
def variables_cualitativas(Caballo_De_Fuerza):
  '''
  1   Si es mayor a la “media + 1*desviación estándar” → Alto
  2   Si está entre “media - 1*desviación estándar” y “media +
      1*desviación estándar” → Medio
  3   Si es menor a la “media - 1*desviación estándar” → Bajo
  '''
  mean = 105.082500
  std = 38.768779

  if Caballo_De_Fuerza > (mean + 1*std):
    return 'Alto'
  elif (mean -1*std) <= Caballo_De_Fuerza <= (mean + 1*std):
    return 'Medio'
  else:
    return 'Bajo'

In [8]:
df['Variables_Cualitativas'] = df['Caballo_De_Fuerza'].apply(variables_cualitativas)
df.head(45)

,Millas_Por_Galon,Cilindros,Pais_Origen,Peso_En_Libras,Desplazamiento,Aceleracion,Nombre,Anyo,Caballo_De_Fuerza,Variables_Cualitativas
0,18.00,8,USA,3504,307.0,12.0,chevrolet chevelle malibu,1/01/1970,130.00,Medio
1,15.00,8,USA,3693,350.0,11.5,buick skylark 320,1/01/1970,165.00,Alto
2,18.00,8,USA,3436,318.0,11.0,plymouth satellite,1/01/1970,150.00,Alto
3,16.00,8,USA,3433,304.0,12.0,amc rebel sst,1/01/1970,150.00,Alto
4,17.00,8,USA,3449,302.0,10.5,ford torino,1/01/1970,140.00,Medio
5,15.00,8,USA,4341,429.0,10.0,ford galaxie 500,1/01/1970,198.00,Alto
6,14.00,8,USA,4354,454.0,9.0,chevrolet impala,1/01/1970,220.00,Alto
7,14.00,8,USA,4312,440.0,8.5,plymouth fury iii,1/01/1970,215.00,Alto
8,14.00,8,USA,4425,455.0,10.0,pontiac catalina,1/01/1970,225.00,Alto
9,15.00,8,USA,3850,390.0,8.5,amc ambassador dpl,1/01/1970,190.00,Alto
10,23.51,4,Europe,3090,133.0,17.5,citroen ds-21 pallas,1/01/1970,115.00,Medio
11,23.51,8,USA,4142,350.0,11.5,chevrolet chevelle concours (sw),1/01/1970,165.00,Alto
12,23.51,8,USA,4034,351.0,11.0,ford torino (sw),1/01/1970,153.00,Alto
13,23.51,8,USA,4166,383.0,10.5,plymouth satellite (sw),1/01/1970,175.00,Alto
14,23.51,8,USA,3850,360.0,11.0,amc rebel sst (sw),1/01/1970,175.00,Alto
15,15.00,8,USA,3563,383.0,10.0,dodge challenger se,1/01/1970,170.00,Alto
16,14.00,8,USA,3609,340.0,8.0,plymouth 'cuda 340,1/01/1970,160.00,Alto
17,23.51,8,USA,3353,302.0,8.0,ford mustang boss 302,1/01/1970,140.00,Medio
18,15.00,8,USA,3761,400.0,9.5,chevrolet monte carlo,1/01/1970,150.00,Alto
19,14.00,8,USA,3086,455.0,10.0,buick estate wagon (sw),1/01/1970,225.00,Alto
20,24.00,4,Japan,2372,113.0,15.0,toyota corona mark ii,1/01/1970,95.00,Medio
21,22.00,6,USA,2833,198.0,15.5,plymouth duster,1/01/1970,95.00,Medio
22,18.00,6,USA,2774,199.0,15.5,amc hornet,1/01/1970,97.00,Medio
23,21.00,6,USA,2587,200.0,16.0,ford maverick,1/01/1970,85.00,Medio
24,27.00,4,Japan,2130,97.0,14.5,datsun pl510,1/01/1970,88.00,Medio
25,26.00,4,Europe,1835,97.0,20.5,volkswagen 1131 deluxe sedan,1/01/1970,46.00,Bajo
26,25.00,4,Europe,2672,110.0,17.5,peugeot 504,1/01/1970,87.00,Medio
27,24.00,4,Europe,2430,107.0,14.5,audi 100 ls,1/01/1970,90.00,Medio
28,25.00,4,Europe,2375,104.0,17.5,saab 99e,1/01/1970,95.00,Medio
29,26.00,4,Europe,2234,121.0,12.5,bmw 2002,1/01/1970,113.00,Medio
30,21.00,6,USA,2648,199.0,15.0,amc gremlin,1/01/1970,90.00,Medio
31,10.00,8,USA,4615,360.0,14.0,ford f250,1/01/1970,215.00,Alto
32,10.00,8,USA,4376,307.0,15.0,chevy c20,1/01/1970,200.00,Alto
33,11.00,8,USA,4382,318.0,13.5,dodge d200,1/01/1970,210.00,Alto
34,9.00,8,USA,4732,304.0,18.5,hi 1200d,1/01/1970,193.00,Alto
35,27.00,4,Japan,2130,97.0,14.5,datsun pl510,1/01/1971,88.00,Medio
36,28.00,4,USA,2264,140.0,15.5,chevrolet vega 2300,1/01/1971,90.00,Medio
37,25.00,4,Japan,2228,113.0,14.0,toyota corona,1/01/1971,95.00,Medio
38,25.00,4,USA,2046,98.0,19.0,ford pinto,1/01/1971,105.08,Medio
39,23.51,4,Europe,1978,97.0,20.0,volkswagen super beetle 117,1/01/1971,48.00,Bajo
40,19.00,6,USA,2634,232.0,13.0,amc gremlin,1/01/1971,100.00,Medio
41,16.00,6,USA,3439,225.0,15.5,plymouth satellite custom,1/01/1971,105.00,Medio
42,17.00,6,USA,3329,250.0,15.5,chevrolet chevelle malibu,1/01/1971,100.00,Medio
43,19.00,6,USA,3302,250.0,15.5,ford torino 500,1/01/1971,88.00,Medio
44,18.00,6,USA,3288,232.0,15.5,amc matador,1/01/1971,100.00,Medio

In [9]:
variables_cualitativas.__doc__

'\n  1   Si es mayor a la “media + 1*desviación estándar” → Alto\n  2   Si está entre “media - 1*desviación estándar” y “media +\n      1*desviación estándar” → Medio\n  3   Si es menor a la “media - 1*desviación estándar” → Bajo\n  '

In [10]:
# EXPORTAR DataFrame a CSV
df.to_csv('/content/drive/MyDrive/Curso_DataScience_peru/clases/13.2_PROYECTO2_27JULIO2023/autos_RespEjer3.csv', index=False)